export const ROT = '#CC2006';
export const WEISS = '#FFFFFF';
export const BLAU = '#00356f';
export const GRAU = '#808080';
export const ALICEBLUE = '#F0F8FF';

export const Colors = {
  COSMOS_BLAU: '#00356F', // von cosmosdirekt.de
  COSMOS_BLAU_OPACITY: (opacity: number) => `rgba(0,53,111,${opacity})`,
  COSMOS_BLAU_HELLER: '#1A4A7E',
  COSMOS_BLAU_HELLER_2: '#4D729A',
  COSMOS_BLAU_HELLER_3: '#99AEC5',
  COSMOS_BLAU_HELLER_4: '#B0D0FA',
  COSMOS_BLAU_HELLER_5: '#EBEFF4',

  COSMOS_HELLBLAU: '#A0CFE7',
  COSMOS_GRUEN: '#B1DB23',
  COSMOS_GRAU: '#EBEBEB',
  COSMOS_GRAU_HELLER: '#D3D3D3',
  COSMOS_GELB: '#ffdf33',
  COSMOS_HELLGELB: '#F9F0D0',
  COSMOS_GRAU_DARKER: GRAU,
  COSMOS_GRAU_DARKER_2: 'rgb(169, 169, 169)',
  COSMOS_BUTTON_GRUEN: '#B1DB23',
  COSMOS_TOOLTIP_BORDER: 'rgba(0, 0, 0, 0.23)',
  COSMOS_FIELD_BORDER: 'rgba(0, 0, 0, 0.23)',
  COSMOS_FIELD_BORDER_FOCUS: '#99AEC5',
  COSMOS_FIELD_BORDER_HOVER: '#00356F',

  COSMOS_APP_BACKGROUND: '#D2DBE5',

  COSMOS_INPUT_BORDER: 'rgba(0, 0, 0, 0.23)',
  COSMOS_INPUT_BACKGROUND: '#EBEFF4',
  COSMOS_INPUT_BACKGROUND_FILLED: WEISS,
  COSMOS_INPUT_BACKGROUND_FOCUSED: ALICEBLUE,
  COSMOS_INPUT_BACKGROUND_UNFOCUSED: WEISS,
  COSMOS_INPUT_FONT_UNFILLED: GRAU,
  COSMOS_INPUT_FONT_FILLED: BLAU,
  COSMOS_DIRTY_FIELD_BACKGROUND: '#F9F0D0', // gleich wie COSMOS_HELLGELB
  COSMOS_DIRTY_FIELD_BORDER: '#fccf0a', // gleich wie COSMOS_HELLGELB
  COSMOS_EMPTY_FIELD_BACKGROUND: '#EBEFF4', // gleich wie COSMOS_BLAU_HELLER_5
  COSMOS_FILLED_FIELD_BACKGROUND: '#FFF', // gleich wie WEISS
  COSMOS_TOGGLE_BUTTON_BORDER: 'rgba(0, 0, 0, 0.12)',

  COSMOS_ORANGE: '#FFA500',
  COSMOS_ROT: ROT,
  COSMOS_NEUANLAGE_ROW_HEADER: '#F0F8FF',

  EINGANG: '#218721',
  AUSGANG: ROT,

  WARNING: '#F9F0D0',
  DANGER: ROT,
  INFO: '#D2DBE5',
  SUCCESS: '#88D498',
  PRIMARY: '#B1DB23',
  DEFAULT: '#19497D',
  COSMOS_LILA: '#800080',

  HIGHLIGHTED: '#A0CFE7',
  SELECTED: '#B1DB23',
  SELECTED_HOVER: '#bbe523',
  UNSELECTED: '#CACACA',
  HIGHLIGHTED_SELECTED: '#B5E04F',

  DISABLED: '#A9A9A9',
  BORDER_DISABLED: '#A9A9A9',

  TABLE_TH_BACKGROUND: '#ebeff4',
  TABLE_ROW_BACKGROUND: WEISS,
  TABLE_ROW_HOVER: '#E2EEFB',
  TABLE_BORDER_SELECTED: WEISS,
  TABLE_BORDER_UNSELECTED: '#ebeff4',

  DEFAULT_BORDER_COLOR: 'rgba(0, 0, 0, 0.23)',
  COSMOS_DISABLED_BG: 'rgba(0, 0, 0, 0.03)',
  COSMOS_DISABLED_SELECTED_BG: 'rgba(0, 0, 0, 0.09)',
};

export const cosmosSpecialFont = 'Univers W01';

export const customSpacing = 4;
